import {
  Heart,
  Drumstick,
  Droplet,
  Moon,
  Thermometer,
  Backpack,
  Dumbbell,
  MapPin,
  Wrench,
  Axe,
  Flashlight,
  Box,
  Hammer,
  HardHat,
  Shirt,
  Hand,
  Glasses,
  Layers,
  Footprints,
  PersonStanding,
  Zap,
  X,
  Club,
  Crosshair,
  CookingPot,
  Target,
  Feather,
  Wind,
  EyeOff,
  Slash,
  Sword,
  Swords,
  Construction,
  Wheat,
  Stethoscope,
  Cog,
  Flame,
  Scissors,
  Fish,
  Trees,
  Leaf,
  Slice,
  FlaskConical,
  Gem,
  BrickWall,
  Anvil,
  Amphora,
  PawPrint,
  Rabbit,
  Beef,
  Tent,
  CircleDot,
  MapPinned,
  Brain,
  AlertTriangle,
  Activity,
  Skull,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  heart: Heart,
  drumstick: Drumstick,
  droplet: Droplet,
  moon: Moon,
  zap: Zap,
  thermometer: Thermometer,
  backpack: Backpack,
  dumbbell: Dumbbell,
  'map-pin': MapPin,
  wrench: Wrench,
  axe: Axe,
  flashlight: Flashlight,
  box: Box,
  hammer: Hammer,
  'hard-hat': HardHat,
  shirt: Shirt,
  hand: Hand,
  glasses: Glasses,
  layers: Layers,
  footprints: Footprints,
  'person-standing': PersonStanding,
  close: X,
  club: Club,
  crosshair: Crosshair,
  'cooking-pot': CookingPot,
  target: Target,
  feather: Feather,
  wind: Wind,
  'eye-off': EyeOff,
  slash: Slash,
  sword: Sword,
  swords: Swords,
  construction: Construction,
  wheat: Wheat,
  stethoscope: Stethoscope,
  cog: Cog,
  flame: Flame,
  scissors: Scissors,
  fish: Fish,
  trees: Trees,
  leaf: Leaf,
  slice: Slice,
  'flask-conical': FlaskConical,
  gem: Gem,
  'brick-wall': BrickWall,
  anvil: Anvil,
  amphora: Amphora,
  'paw-print': PawPrint,
  rabbit: Rabbit,
  beef: Beef,
  tent: Tent,
  'circle-dot': CircleDot,
  'map-pinned': MapPinned,
  brain: Brain,
  'alert-triangle': AlertTriangle,
  activity: Activity,
  skull: Skull,
};

export function Icon({
  name,
  size = 20,
  color,
  strokeWidth = 2,
}: {
  name: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}) {
  const Cmp = ICONS[name];
  if (!Cmp) return null;
  return <Cmp size={size} color={color} strokeWidth={strokeWidth} />;
}
